services:
  freebin-db:
    container_name: freebin-db
    image: postgres:17-alpine
    environment: 
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

    healthcheck:
      interval: 5s
      retries: 5
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      timeout: 5s

    ports:
      - "5432:5432"

